server:
  port: 8333

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wustyjs?serverTimezone=Asia/Shanghai&useSSL=false
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher   # 解决springboot高版本与swagger冲突的问题
  profiles:
    # dev/prod
    active: dev

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml